name: Angular-App-AutoBuild&Test

on: 
  push:
    branches: master
    paths-ignore:
        - 'node_server/**'
        - '.github/**'
        - 'dist/**'
jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run test
        npm run build --if-present
      env:
        CI: true
